### ISSUE TITLE
Not taking a snapshot of the <head> correctly

### ISSUE THREAD

**Issue by alimovz** [lifeart/dom-snapshot#145]
Maybe I am missing something, but why does this head:
```
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css"/>
    <title>Test Website</title>
</head>
```

is snapped like this:
![Untitled](https://github.com/user-attachments/assets/a67402df-6444-4da7-89fe-a97a16c387ea)

It's just a bunch of text nodes. Why doesn't it capture my style sheet tags?

**Comment by lifeart** [comment]
Hi @alimovz! We compute styles in runtime (during snapshot creation), that's why we skipping all style tags

**Comment by alimovz** [comment]
Got it. I am taking a snapshot of the body like so:
```
var selector  = 'body';
var s1 = snapshoter.takeSnapshot(selector);
console.log(JSON.stringify(s1));
```
and storing the stringified version of the snapshot in my own database. I see that one way to convert the object back into a dom element is by running `snapshot.showSnapshot(id)`. But if I don't have a firebase id for it? What if I just want to feed a snapshot object into a function and have it generate a dom element. How can I do that?

**Comment by lifeart** [comment]
It's possible to use api without firebase:

```js
// store
const snapshoter = new DomSnapshot();
var s1 = snapshoter.takeSnapshot(selector);

// restore
const ELEMENT_TO_RESTORE_SNAPSHOT_TO = document.body;
snapshoter.destroyWorld();
snapshoter.setState(snapshoter, s1);
snapshoter.restoreWorldFrom(snapshoter, ELEMENT_TO_RESTORE_SNAPSHOT_TO);

```
