### ISSUE TITLE
new DomSnapshot();   not defined

### ISSUE THREAD

**Issue by QGB** [lifeart/dom-snapshot#64]
Uncaught ReferenceError: DomSnapshot is not defined

html include dom-snapshot <script> tag

**Comment by lifeart** [comment]
Hi @QGB thank you for report, will check it

**Comment by lifeart** [comment]
fixed in https://github.com/lifeart/dom-snapshot/commit/20fa2b2fb0de5d65edb43a2064d61d9e1a5060a9
